# Global Settings Configuration
# This file contains all the global settings for your site

# Site Information
site:
  title: "Maglev Documentation"

appearance:
  theme: "light"

# Features
features:
  analytics_enabled: true
  search_enabled: true

# SEO
seo:
  plausible_domain: "docs.maglev.dev"
  meta_description: "Documentation for the Maglev framework"
  meta_keywords: "maglev, documentation, framework"
